{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "447822d1-c42b-47a9-99da-d44571d5df9c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "\n",
    "# ---------------- PAGE CONFIG ----------------\n",
    "st.set_page_config(\n",
    "    page_title=\"Rishana Abubacker | Senior Data Analyst\",\n",
    "    page_icon=\"📊\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# ---------------- HEADER ----------------\n",
    "st.title(\"Rishana Abubacker\")\n",
    "st.subheader(\"Senior Data Analyst | Product, Business & GenAI Analytics\")\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "Senior Data Analyst with 4+ years of experience turning complex, high-volume data into\n",
    "clear, actionable insights that drive business, product, and customer decisions.\n",
    "\n",
    "Delivered analytics across **60+ engagements for Tier-1 clients**, supporting global\n",
    "Consumer and Healthcare brands. Specialized in **SQL-driven analytics, automation,\n",
    "dashboarding, and LLM-powered insight extraction**.\n",
    "\"\"\")\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# ---------------- METRICS ----------------\n",
    "col1, col2, col3, col4 = st.columns(4)\n",
    "col1.metric(\"Experience\", \"4+ Years\")\n",
    "col2.metric(\"Tier-1 Engagements\", \"60+\")\n",
    "col3.metric(\"Data Scale\", \"30M+ Records\")\n",
    "col4.metric(\"Decision Velocity\", \"↑ 40%\")\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# ---------------- SKILLS ----------------\n",
    "st.header(\"🧠 Core Skills\")\n",
    "\n",
    "col1, col2 = st.columns(2)\n",
    "\n",
    "with col1:\n",
    "    st.markdown(\"\"\"\n",
    "**Data Analysis & SQL**\n",
    "- Advanced SQL (CTEs, window functions, complex joins)\n",
    "- Exploratory data analysis & root cause analysis\n",
    "- Metric ownership (NPS, churn, sentiment)\n",
    "- Hypothesis-driven analysis\n",
    "\"\"\")\n",
    "\n",
    "with col2:\n",
    "    st.markdown(\"\"\"\n",
    "**Tools & Advanced Analytics**\n",
    "- Python for automation & data processing\n",
    "- Tableau dashboards & KPI frameworks\n",
    "- LLM prompt engineering for insight extraction\n",
    "- Competitor benchmarking & investor analytics\n",
    "\"\"\")\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# ---------------- EXPERIENCE ----------------\n",
    "st.header(\"💼 Experience Summary\")\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "As a Senior Data Analyst, I work closely with consultants, investors, product teams,\n",
    "and CX leaders to support data-backed decision-making at scale.\n",
    "\n",
    "**Key responsibilities include:**\n",
    "- Owning analytics across NPS, customer support tickets, reviews, and feedback\n",
    "- Building SQL-driven pipelines and Tableau dashboards\n",
    "- Conducting churn and root-cause deep dives\n",
    "- Delivering competitor benchmarking for investment decisions\n",
    "- Applying LLM-powered insight extraction to scale qualitative analysis\n",
    "- Automating workflows, improving efficiency by ~60%\n",
    "\"\"\")\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# ---------------- PROJECTS ----------------\n",
    "st.header(\"🧩 Flagship Projects\")\n",
    "\n",
    "with st.expander(\"📊 NPS & Customer Sentiment Analytics Platform\", expanded=True):\n",
    "    st.markdown(\"\"\"\n",
    "**Problem**  \n",
    "Lack of a unified view of customer sentiment across surveys, reviews, and support tickets.\n",
    "\n",
    "**Approach**\n",
    "- SQL pipelines consolidating NPS, review text, and ticket data\n",
    "- Tableau dashboards tracking sentiment drivers and trends\n",
    "- Root cause analysis of dissatisfaction drivers\n",
    "\n",
    "**Impact**\n",
    "- 5–30% reduction in customer negativity\n",
    "- ~40% faster decision-making\n",
    "\"\"\")\n",
    "\n",
    "with st.expander(\"🔁 Customer Churn & Retention Deep Dive\"):\n",
    "    st.markdown(\"\"\"\n",
    "**Problem**  \n",
    "Unclear drivers of customer churn and retention risks.\n",
    "\n",
    "**Approach**\n",
    "- Advanced SQL analysis of customer interactions\n",
    "- Identification of high-impact churn indicators\n",
    "- Stakeholder collaboration on retention initiatives\n",
    "\n",
    "**Impact**\n",
    "- Supported ~20% churn reduction initiatives\n",
    "\"\"\")\n",
    "\n",
    "with st.expander(\"📈 Competitor Benchmarking for Investors\"):\n",
    "    st.markdown(\"\"\"\n",
    "**Problem**  \n",
    "Need for data-backed competitive benchmarking.\n",
    "\n",
    "**Approach**\n",
    "- Comparative dashboards across competing brands\n",
    "- Review and sentiment analysis\n",
    "- Risk and opportunity identification\n",
    "\n",
    "**Impact**\n",
    "- Informed investment and due-diligence decisions\n",
    "\"\"\")\n",
    "\n",
    "with st.expander(\"🛠 Product Improvement Prioritization\"):\n",
    "    st.markdown(\"\"\"\n",
    "**Problem**  \n",
    "Fragmented customer feedback limited product prioritization.\n",
    "\n",
    "**Approach**\n",
    "- SQL-based mapping of issues to product features\n",
    "- Frequency, sentiment, and trend analysis\n",
    "\n",
    "**Impact**\n",
    "- Informed product improvements for ~60% of consumer clients\n",
    "\"\"\")\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# ---------------- IMPACT ----------------\n",
    "st.header(\"🚀 Impact & Outcomes\")\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "- 📉 5–30% reduction in customer negativity  \n",
    "- 🔁 ~20% churn reduction (initiative-supported)  \n",
    "- 🧠 Product improvements for ~60% of clients  \n",
    "- 🚀 40% improvement in decision velocity  \n",
    "- 🤖 50%+ reduction in manual qualitative analysis using LLMs  \n",
    "\"\"\")\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# ---------------- CONTACT ----------------\n",
    "st.header(\"📬 Let’s Connect\")\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "- **LinkedIn:** https://www.linkedin.com/in/rishana-abubacker-54045713b/\n",
    "- **Email:** rishanaabubacker.abc@gmail.com\n",
    "\"\"\")\n",
    "\n",
    "st.caption(\"Open to Senior Data Analyst, BI Engineer, and Product Analytics roles.\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
